@startuml
allowmixing

left to right direction

package language-extensions {
  package plcc-java {
    class plcc-java-emit
    class plcc-java-build
    class plcc-java-run
  }

  package plcc-python {
    class plcc-python-emit
    class plcc-python-build
    class plcc-python-run
  }
}

package parser-extensions {
  package plcc-parser-table {
    class plcc-parser-table
  }
}

package diagram-extensions {
  package plcc-mermaid-diagram {
    class plcc-mermaid-diagram-emit
    class plcc-mermaid-diagram-build
    class plcc-mermaid-diagram-run
  }

  package plcc-plantuml-diagram {
    class plcc-plantuml-diagram-emit
    class plcc-plantuml-diagram-build
    class plcc-plantuml-diagram-run
  }
}

package core {

  class plcc-version
  class plcc-lang-list
  class plcc-parser-list

  plcc-scan --> plcc-make
  plcc-scan --> plcc-tokens

  plcc-parse --> plcc-make
  plcc-parse --> plcc-tokens
  plcc-parse --> plcc-trees

  plcc-rep --> plcc-make
  plcc-rep --> plcc-tokens
  plcc-rep --> plcc-trees
  plcc-rep --> plcc-lang-run

  plcc-make --> plcc-spec
  plcc-make --> plcc-ll1
  plcc-make --> plcc-model
  plcc-make --> plcc-lang-emit
  plcc-make --> plcc-lang-build

  plcc-trees --> parser-extensions.plcc-parser-table.plcc-parser-table

  plcc-lang-emit --> plcc-python-emit
  plcc-lang-emit --> plcc-java-emit
  plcc-lang-build --> plcc-java-build
  plcc-lang-build --> plcc-python-build
  plcc-lang-run --> plcc-python-run
  plcc-lang-run --> plcc-java-run

}

package plcc-diagram {

  class plcc-diagram-list

  plcc-diagram --> plcc-make
  plcc-diagram --> plcc-diagram-emit
  plcc-diagram --> plcc-diagram-build
  plcc-diagram --> plcc-diagram-run

  plcc-diagram-emit --> plcc-mermaid-diagram-emit
  plcc-diagram-emit --> plcc-plantuml-diagram-emit
  plcc-diagram-build --> plcc-mermaid-diagram-build
  plcc-diagram-build --> plcc-plantuml-diagram-build
  plcc-diagram-run --> plcc-mermaid-diagram-run
  plcc-diagram-run --> plcc-plantuml-diagram-run

}

actor "Language Author" as author

author --> plcc-scan
author --> plcc-parse
author --> plcc-rep
author --> plcc-version
author --> plcc-lang-list
author --> plcc-parser-list
author --> plcc-diagram
author --> plcc-diagram-list

@enduml
