---
name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: jveldboom/action-conventional-versioning@v1
        id: version

      - name: Update Major Tag
        env:
          MAJOR: ${{ steps.version.outputs.major }}
          MINOR: ${{ steps.version.outputs.minor }}
          PATCH: ${{ steps.version.outputs.patch }}
        run: |
          git tag ${MAJOR}.${MINOR}.${PATCH} ${GITHUB_SHA} || true
          git push origin ${MAJOR}.${MINOR}.${PATCH} || true

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "${{ steps.version.outputs.version }}" \
            --generate-notes \
            --target "${{ github.sha }}"
