---
name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: jveldboom/action-conventional-versioning@v1
        id: version

      - name: Update Major Tag
        env:
          MAJOR: ${{ steps.version.outputs.major }}
        run: |
          git tag -d ${MAJOR} || true
          git push origin :refs/tags/${MAJOR} || true
          git tag ${MAJOR} ${GITHUB_SHA} || true
          git push origin ${MAJOR} || true
          git tag -d ${MAJOR}.${MINOR} || true
          git push origin :refs/tags/${MAJOR}.${MINOR} || true
          git tag ${MAJOR}.${MINOR} ${GITHUB_SHA} || true
          git push origin ${MAJOR}.${MINOR} || true
          git tag ${MAJOR}.${MINOR}.${PATCH} ${GITHUB_SHA} || true
          git push origin ${MAJOR}.${MINOR}.${PATCH} || true

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "${{ steps.version.outputs.version-with-prefix }}" \
            --generate-notes \
            --target "${{ github.sha }}"
